//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/VR Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VR Controls"",
    ""maps"": [
        {
            ""name"": ""VR action map"",
            ""id"": ""44733947-d08c-472b-8534-3d4560020e4b"",
            ""actions"": [
                {
                    ""name"": ""Reset Pins"",
                    ""type"": ""Button"",
                    ""id"": ""f316912e-767a-4b56-863b-c532a1ac0217"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""98a8bedb-ea99-4e5a-ae06-186b62b5dd79"",
                    ""path"": ""<XRController>{RightHand}/touchpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset Pins"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VR action map
        m_VRactionmap = asset.FindActionMap("VR action map", throwIfNotFound: true);
        m_VRactionmap_ResetPins = m_VRactionmap.FindAction("Reset Pins", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VR action map
    private readonly InputActionMap m_VRactionmap;
    private IVRactionmapActions m_VRactionmapActionsCallbackInterface;
    private readonly InputAction m_VRactionmap_ResetPins;
    public struct VRactionmapActions
    {
        private @VRControls m_Wrapper;
        public VRactionmapActions(@VRControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ResetPins => m_Wrapper.m_VRactionmap_ResetPins;
        public InputActionMap Get() { return m_Wrapper.m_VRactionmap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRactionmapActions set) { return set.Get(); }
        public void SetCallbacks(IVRactionmapActions instance)
        {
            if (m_Wrapper.m_VRactionmapActionsCallbackInterface != null)
            {
                @ResetPins.started -= m_Wrapper.m_VRactionmapActionsCallbackInterface.OnResetPins;
                @ResetPins.performed -= m_Wrapper.m_VRactionmapActionsCallbackInterface.OnResetPins;
                @ResetPins.canceled -= m_Wrapper.m_VRactionmapActionsCallbackInterface.OnResetPins;
            }
            m_Wrapper.m_VRactionmapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ResetPins.started += instance.OnResetPins;
                @ResetPins.performed += instance.OnResetPins;
                @ResetPins.canceled += instance.OnResetPins;
            }
        }
    }
    public VRactionmapActions @VRactionmap => new VRactionmapActions(this);
    public interface IVRactionmapActions
    {
        void OnResetPins(InputAction.CallbackContext context);
    }
}
